### ISSUE TITLE
Explaining DSC keywords throws exceptions on DevContainer

### ISSUE THREAD

**Issue by Jawz84** [Jawz84/explainpowershell#35]
When sending 

```powershell
configuration MyDscConfig {sdf}
```

```text
# log
[2021-06-12T19:53:44.338Z] Executing 'SyntaxAnalyzer' (Reason='This function was programmatically called via the host APIs.', Id=f5f0071b-c60e-4893-a083-0f6903777f82)
[2021-06-12T19:53:44.339Z] PowerShell code sent: configuration MyDscConfig {sdf}
Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSEtwLog' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Management.Automation.Tracing.PSSysLogProvider' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libpsl-native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibpsl-native: cannot open shared object file: No such file or directory
   at System.Management.Automation.Tracing.NativeMethods.OpenLog(IntPtr ident, SysLogPriority facility)
   at System.Management.Automation.Tracing.SysLogProvider..ctor(String applicationId, PSLevel level, PSKeyword keywords, PSChannel channels)
   at System.Management.Automation.Tracing.PSSysLogProvider..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Tracing.PSSysLogProvider..ctor()
   at System.Management.Automation.Tracing.PSEtwLog..cctor()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Tracing.PSEtwLog.LogOperationalInformation(PSEventId id, PSOpcode opcode, PSTask task, PSKeyword keyword, Object[] args)
   at System.Management.Automation.Remoting.RemoteSessionNamedPipeServer.ProcessListeningThread(Object state)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

website hangs:

**Comment by Jawz84** [comment]
Moved away from devcontainers
